Entity/BarionItem.php
<?php

namespace Vaszev\BarionBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;


/**
 * @ORM\Entity(repositoryClass="Vaszev\BarionBundle\Repository\BarionItemRepository")
 */
class BarionItem extends Base {

  /**
   * @var string
   * @ORM\Column(name="name", type="string", length=255)
   */
  private $Name;

  /**
   * @var string
   * @ORM\Column(name="description", type="text", length=500)
   * @Assert\NotBlank()
   */
  private $Description;

  /**
   * @var int
   * @ORM\Column(name="quantity", type="integer")
   * @Assert\GreaterThan(value="0")
   */
  private $Quantity;

  /**
   * @var string
   * @ORM\Column(name="unit", type="string", length=255)
   */
  private $Unit = "piece";

  /**
   * @var float
   * @ORM\Column(name="unit_price", type="decimal", precision=17, scale=2)
   * @Assert\GreaterThan(value="0")
   */
  private $UnitPrice;

  /**
   * @var float
   * @Assert\GreaterThan(value="0")
   * @ORM\Column(name="item_total", type="decimal", precision=17, scale=2)
   */
  private $ItemTotal;

  /**
   * @var string
   * @ORM\Column(name="sku", type="string", length=255)
   */
  private $SKU;

  /**
   * @ORM\ManyToOne(targetEntity="BarionPaymentTransaction", inversedBy="Items")
   * @Assert\NotNull()
   */
  private $Transaction;



  /**
   * @return mixed
   */
  public function getTransaction() {
    return $this->Transaction;
  }



  /**
   * @param mixed $Transaction
   * @return $this
   */
  public function setTransaction($Transaction) {
    $this->Transaction = $Transaction;

    return $this;
  }



  /**
   * @return string
   */
  public function getName(): ?string {
    return $this->Name;
  }



  /**
   * @param string $Name
   * @return $this
   */
  public function setName($Name) {
    $this->Name = $Name;

    return $this;
  }



  /**
   * @return string
   */
  public function getDescription(): ?string {
    return $this->Description;
  }



  /**
   * @param string $Description
   * @return $this
   */
  public function setDescription($Description) {
    $this->Description = $Description;

    return $this;
  }



  /**
   * @return int
   */
  public function getQuantity(): ?int {
    return $this->Quantity;
  }



  /**
   * @param int $Quantity
   * @return $this
   */
  public function setQuantity($Quantity) {
    $this->Quantity = $Quantity;

    return $this;
  }



  /**
   * @return string
   */
  public function getUnit(): ?string {
    return $this->Unit;
  }



  /**
   * @param string $Unit
   * @return $this
   */
  public function setUnit($Unit) {
    $this->Unit = $Unit;

    return $this;
  }



  /**
   * @return float
   */
  public function getUnitPrice(): ?float {
    return $this->UnitPrice;
  }



  /**
   * @param float $UnitPrice
   * @return $this
   */
  public function setUnitPrice($UnitPrice) {
    $this->UnitPrice = $UnitPrice;

    return $this;
  }



  /**
   * @return float
   */
  public function getItemTotal(): ?float {
    return $this->ItemTotal;
  }



  /**
   * @param float $ItemTotal
   * @return $this
   */
  public function setItemTotal($ItemTotal) {
    $this->ItemTotal = $ItemTotal;

    return $this;
  }



  /**
   * @return string
   */
  public function getSKU(): ?string {
    return $this->SKU;
  }



  /**
   * @param string $SKU
   * @return $this
   */
  public function setSKU($SKU) {
    $this->SKU = $SKU;

    return $this;
  }


}

Entity/BarionPaymentRequest.php
<?php

namespace Vaszev\BarionBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Vaszev\BarionBundle\Service\Currency;
use Vaszev\BarionBundle\Service\FundingSourceType;
use Vaszev\BarionBundle\Service\PaymentType;
use Vaszev\BarionBundle\Service\UILocale;

/**
 * @ORM\Entity(repositoryClass="Vaszev\BarionBundle\Repository\BarionPaymentRequestRepository")
 */
class BarionPaymentRequest extends Base {

  /**
   * @var string
   * @ORM\Column(name="payment_type", type="string", length=255)
   */
  private $PaymentType = PaymentType::Immediate;

  /**
   * @var string
   * TimeSpan (d:hh:mm:ss)
   * Required only if PaymentType is "Reservation"
   * Minimum value: one minute
   * Maximum value: one year
   * Default value: 30 minutes
   */
  private $ReservationPeriod;

  /**
   * @var string
   * TimeSpan (d:hh:mm:ss)
   * Time window for the payment to be completed. The payer must execute the payment before this elapses, or else the payment will expire and can no longer be completed.
   * Optional
   * Minimum value: one minute
   * Maximum value: one week
   * Default value: 30 minutes
   */
  private $PaymentWindow;

  /**
   * @var bool
   * Flag indicating wether the payment can be completed without a registered Barion wallet. Guest checkout can only be done with bank cards, and the payer must supply a valid e-mail address - this is necessary for fraud control.
   * @ORM\Column(name="guest_checkout", type="boolean")
   */
  private $GuestCheckout = true;

  /**
   * @var array
   * An array of strings containing the allowed funding sources that can be used to complete the payment. "Balance" means that the payer can only use their Barion wallet balance, while "All" means the payment can be completed with either a Barion wallet or a bank card.
   * @ORM\Column(name="funding_sources", type="array")
   */
  private $FundingSources = [FundingSourceType::All];

  /**
   * @var string
   * The shop can optionally supply an e-mail address as a hint on who should complete the payment. This can be used if the shop is certain about that the payer has an active Barion wallet or the shop would like to help the guest payer with filling in the email field for her/him. If provided, the Barion Smart Gateway automatically fills out the e-mail address field in the Barion wallet login form and the guest payer form, speeding up the payment process.
   * @ORM\Column(name="payer_hint", type="string", length=255)
   * @Assert\Email()
   */
  private $PayerHint;

  /**
   * @ORM\OneToMany(targetEntity="BarionPaymentTransaction", mappedBy="Request")
   * @Assert\Count(min=1)
   */
  private $Transactions;

  /**
   * @var string
   * @ORM\Column(name="locale", type="string", length=255)
   */
  private $Locale = UILocale::HU;

  /**
   * @var string
   * @ORM\Column(name="shipping_address", type="string", length=255)
   */
  private $ShippingAddress;

  /**
   * @var bool
   * This flag indicates that the shop would like to initialize a token payment. This means that the shop is authorized to charge the funding source of the payer in the future without redirecting her/him to the Barion Smart Gateway. It can be used for one-click and susbscription payment scenarios.
   */
  private $InitiateRecurrence;

  /**
   * @var string
   * A string used to identify a given authorized payment. Its purpose is determined by the value of the InitiateRecurrence property.
   * If InitiateRecurrence is true, this property must contain a new desired identifier for a new authorized payment. This should be generated and stored by the shop before calling the  API. Also the shop must ensure that this is unique per user in its own system.
   * If InitiateRecurrence is false, this property must contain an existing identifier for an authorized payment. This should be used to charge a payer's funding source (either bank card or Barion wallet) that was already used successfully for a payment in the shop.
   */
  private $RecurrenceId;

  /**
   * will be our waiting room
   * @var string
   * @ORM\Column(name="redirect_url", type="string", length=255)
   */
  private $RedirectUrl;

  /**
   * user's webshop redirection after all
   * @var string
   * @ORM\Column(name="saved_redirect_url", type="string", length=255)
   */
  private $SavedRedirectUrl;

  /**
   * will be our callback listener
   * @var string
   * @ORM\Column(name="callback_url", type="string", length=255)
   */
  private $CallbackUrl;

  /**
   * @var string
   * @ORM\Column(name="currency", type="string", length=255)
   */
  private $Currency = Currency::HUF;

  /**
   * @ORM\OneToOne(targetEntity="BarionPaymentResponse", mappedBy="PaymentRequest")
   */
  private $PaymentResponse;

  /**
   * @ORM\OneToMany(targetEntity="BarionPaymentStateResponse", mappedBy="PaymentRequest")
   * @ORM\OrderBy({"edited"="DESC"})
   */
  private $PaymentStates;



  /**
   * BarionPaymentRequest constructor.
   */
  public function __construct() {
    parent::__construct();
    $this->Transactions = new ArrayCollection();
    $this->PaymentStates = new ArrayCollection();
  }



  /**
   * @return string
   */
  public function getSavedRedirectUrl(): string {
    return $this->SavedRedirectUrl;
  }



  /**
   * @param string $SavedRedirectUrl
   * @return $this
   */
  public function setSavedRedirectUrl($SavedRedirectUrl) {
    $this->SavedRedirectUrl = $SavedRedirectUrl;

    return $this;
  }



  /**
   * @return mixed
   */
  public function getPaymentStates() {
    return $this->PaymentStates;
  }



  /**
   * @return BarionPaymentResponse
   */
  public function getPaymentResponse() {
    return $this->PaymentResponse;
  }



  /**
   * @return mixed
   */
  public function getTransactions() {
    return $this->Transactions;
  }



  /**
   * @return string
   */
  public function getPaymentType(): ?string {
    return $this->PaymentType;
  }



  /**
   * @param string $PaymentType
   * @return $this
   */
  public function setPaymentType($PaymentType) {
    $this->PaymentType = $PaymentType;

    return $this;
  }



  /**
   * @return mixed
   */
  public function getReservationPeriod() {
    return $this->ReservationPeriod;
  }



  /**
   * @param mixed $ReservationPeriod
   * @return $this
   */
  public function setReservationPeriod($ReservationPeriod) {
    $this->ReservationPeriod = $ReservationPeriod;

    return $this;
  }



  /**
   * @return mixed
   */
  public function getPaymentWindow() {
    return $this->PaymentWindow;
  }



  /**
   * @param mixed $PaymentWindow
   * @return $this
   */
  public function setPaymentWindow($PaymentWindow) {
    $this->PaymentWindow = $PaymentWindow;

    return $this;
  }



  /**
   * @return bool
   */
  public function isGuestCheckout(): bool {
    return (bool)$this->GuestCheckout;
  }



  /**
   * @param bool $GuestCheckout
   * @return $this
   */
  public function setGuestCheckout($GuestCheckout) {
    $this->GuestCheckout = $GuestCheckout;

    return $this;
  }



  /**
   * @return array
   */
  public function getFundingSources(): ?array {
    return $this->FundingSources;
  }



  /**
   * @param array $FundingSources
   * @return $this
   */
  public function setFundingSources($FundingSources) {
    $this->FundingSources = $FundingSources;

    return $this;
  }



  /**
   * @return string
   */
  public function getPayerHint(): ?string {
    return $this->PayerHint;
  }



  /**
   * @param string $PayerHint
   * @return $this
   */
  public function setPayerHint($PayerHint) {
    $this->PayerHint = $PayerHint;

    return $this;
  }



  /**
   * @return string
   */
  public function getLocale(): ?string {
    return $this->Locale;
  }



  /**
   * @param string $Locale
   * @return $this
   */
  public function setLocale($Locale) {
    $this->Locale = $Locale;

    return $this;
  }



  /**
   * @return string
   */
  public function getShippingAddress(): ?string {
    return $this->ShippingAddress;
  }



  /**
   * @param string $ShippingAddress
   * @return $this
   */
  public function setShippingAddress($ShippingAddress) {
    $this->ShippingAddress = $ShippingAddress;

    return $this;
  }



  /**
   * @return mixed
   */
  public function getInitiateRecurrence() {
    return $this->InitiateRecurrence;
  }



  /**
   * @param mixed $InitiateRecurrence
   * @return $this
   */
  public function setInitiateRecurrence($InitiateRecurrence) {
    $this->InitiateRecurrence = $InitiateRecurrence;

    return $this;
  }



  /**
   * @return mixed
   */
  public function getRecurrenceId() {
    return $this->RecurrenceId;
  }



  /**
   * @param mixed $RecurrenceId
   * @return $this
   */
  public function setRecurrenceId($RecurrenceId) {
    $this->RecurrenceId = $RecurrenceId;

    return $this;
  }



  /**
   * @return string
   */
  public function getRedirectUrl(): ?string {
    return $this->RedirectUrl;
  }



  /**
   * @param string $RedirectUrl
   * @return $this
   */
  public function setRedirectUrl($RedirectUrl) {
    $this->RedirectUrl = $RedirectUrl;

    return $this;
  }



  /**
   * @return string
   */
  public function getCallbackUrl(): ?string {
    return $this->CallbackUrl;
  }



  /**
   * @param string $CallbackUrl
   * @return $this
   */
  public function setCallbackUrl($CallbackUrl) {
    $this->CallbackUrl = $CallbackUrl;

    return $this;
  }



  /**
   * @return string
   */
  public function getCurrency(): ?string {
    return $this->Currency;
  }



  /**
   * @param string $Currency
   * @return $this
   */
  public function setCurrency($Currency) {
    $this->Currency = $Currency;

    return $this;
  }


}

Entity/BarionPaymentResponse.php
<?php

namespace Vaszev\BarionBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="Vaszev\BarionBundle\Repository\BarionPaymentResponseRepository")
 */
class BarionPaymentResponse extends Base {

  /**
   * @var string
   * @ORM\Column(name="payment_id", type="string", length=255)
   */
  private $PaymentId;

  /**
   * @ORM\OneToOne(targetEntity="BarionPaymentRequest", inversedBy="PaymentResponse")
   * @ORM\JoinColumn(name="payment_request_id", referencedColumnName="id")
   */
  private $PaymentRequest;

  /**
   * @var string
   * @ORM\Column(name="status", type="string", length=255)
   */
  private $Status;

  /**
   * @var array
   * An array containing all transactions associated with the payment. If the Barion system deducts fees from the shop after payments, this also contains these additional fee transactions beside the payment transactions that were sent in the request.
   * currently disabled
   */
  private $Transactions;

  /**
   * @var string
   * @ORM\Column(name="qrurl", type="string", length=255)
   */
  private $QRUrl;

  /**
   * @var string
   * @ORM\Column(name="recurrence_result", type="string", length=255)
   */
  private $RecurrenceResult;

  /**
   * @var string
   * @ORM\Column(name="payment_redirect_url", type="string", length=255)
   */
  private $PaymentRedirectUrl;



  /**
   * @return string
   */
  public function getPaymentId(): ?string {
    return $this->PaymentId;
  }



  /**
   * @param string $PaymentId
   * @return $this
   */
  public function setPaymentId($PaymentId) {
    $this->PaymentId = $PaymentId;

    return $this;
  }



  /**
   * @return mixed
   */
  public function getPaymentRequest() {
    return $this->PaymentRequest;
  }



  /**
   * @param mixed $PaymentRequest
   * @return $this
   */
  public function setPaymentRequest($PaymentRequest) {
    $this->PaymentRequest = $PaymentRequest;

    return $this;
  }



  /**
   * @return string
   */
  public function getStatus(): ?string {
    return $this->Status;
  }



  /**
   * @param string $Status
   * @return $this
   */
  public function setStatus($Status) {
    $this->Status = $Status;

    return $this;
  }



  /**
   * @return string
   */
  public function getQRUrl(): ?string {
    return $this->QRUrl;
  }



  /**
   * @param string $QRUrl
   * @return $this
   */
  public function setQRUrl($QRUrl) {
    $this->QRUrl = $QRUrl;

    return $this;
  }



  /**
   * @return string
   */
  public function getRecurrenceResult(): ?string {
    return $this->RecurrenceResult;
  }



  /**
   * @param string $RecurrenceResult
   * @return $this
   */
  public function setRecurrenceResult($RecurrenceResult) {
    $this->RecurrenceResult = $RecurrenceResult;

    return $this;
  }



  /**
   * @return string
   */
  public function getPaymentRedirectUrl(): ?string {
    return $this->PaymentRedirectUrl;
  }



  /**
   * @param string $PaymentRedirectUrl
   * @return $this
   */
  public function setPaymentRedirectUrl($PaymentRedirectUrl) {
    $this->PaymentRedirectUrl = $PaymentRedirectUrl;

    return $this;
  }


}

Resources/views/barion/pixel.html.twig
<script>
  (function(i,s,o,g,r,a,m){i['BarionAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window, document, 'script', 'https://pixel.barion.com/bp.js', 'bp');

  // send page view event
  bp('init', 'addBarionPixelId', '{{ pixelId }}');
</script>

<noscript>
  <img height="1" width="1" style="display:none" src="https://pixel.barion.com/a.gif?__ba_pixel_id={{ pixelId }}&ev=contentView&noscript=1"/>
</noscript>

Resources/views/barion/waitingRoom.html.twig
<!DOCTYPE html>
<html lang="hu">
<head>
  <meta charset="UTF-8">
  <meta name="robots" content="noindex,noarchive">
  <title>Barion smart gateway</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
  <link href="https://fonts.googleapis.com/css?family={{ waitingRoomGoogleFont|default('Lato')|url_encode }}&amp;subset=latin-ext" rel="stylesheet">
  <style>
    html {
      height: 100vh;
    }

    body {
      font-family: '{{ waitingRoomGoogleFont|default('Lato') }}', sans-serif;
      height: 100vh;
      background-color: {{ waitingRoomBg }};
      color: {{ waitingRoomColor }};
      font-size: calc(14px + 0.5vw);
      margin: 0;
      overflow-y: hidden;
    }

    h1 {
      font-size: 2em;
      margin: 0;
    }

    h2, h3 {
      font-size: 1.5em;
      margin: 0;
    }

    strong {
      color: {{ waitingRoomAmountColor }};
    }

    img {
      padding: 1rem;
      background-color: #fff;
      max-width: calc(100% - 2rem);
    }

    .content {
      height: 100vh;
      display: flex;
      flex-flow: column;
      flex-wrap: wrap;
      align-items: center;
      justify-content: space-evenly;
      text-align: center;
      max-width: 85vw;
      margin: 0 auto;
      overflow: hidden;
    }

    .result {
      display: block;
      padding: 2vh 5vw;
      font-size: 2em;
      color: #fff;
      border-radius: 5px;
      text-transform: uppercase;
      letter-spacing: 3px;
      max-width: 75vw;
      text-overflow: ellipsis;
      overflow: hidden;
    }

    .msg {
      font-style: italic;
      color: tomato;
    }

    .back {
      text-decoration: none;
      color: {{ waitingRoomColor }};
      border: 2px solid{{ waitingRoomColor }};
      padding: 2vh 5vw;
      text-transform: uppercase;
      border-radius: 5px;
      overflow: hidden;
      text-overflow: ellipsis;
      max-width: calc(75vw - 4px);
    }

    .progressbar {
      counter-reset: step;
      width: 85vw;
      min-width: 300px;
      max-width: 900px;
      padding-inline-start: 0;
      display: flex;
      justify-content: center;
      margin: 0;
    }

    .progressbar li {
      list-style-type: none;
      width: 25%;
      float: left;
      position: relative;
      text-align: center;
      text-transform: uppercase;
      color: {{ waitingRoomColor }};
    }

    .progressbar li:before {
      width: 3rem;
      height: 3rem;
      content: counter(step);
      counter-increment: step;
      line-height: 3rem;
      border: 3px solid{{ waitingRoomColor }};
      display: block;
      text-align: center;
      margin: 0 auto 10px auto;
      border-radius: 50%;
      background-color: {{ waitingRoomBg }};
    }

    .progressbar li:after {
      width: 100%;
      height: 5px;
      content: '';
      position: absolute;
      background-color: {{ waitingRoomColor }};
      top: 1.5rem;
      left: -50%;
      z-index: -1;
    }

    .progressbar li:first-child:after {
      content: none;
    }

    .progressbar li.active {
      color: {{ waitingRoomColor }};
    }

    .progressbar li.active:before {
      border-color: {{ waitingRoomPositiveFeedbackColor }};
      background-color: {{ waitingRoomPositiveFeedbackColor }};
    }

    .progressbar li.active + li:after {
      background-color: {{ waitingRoomPositiveFeedbackColor }};
    }
  </style>
</head>
<body>
<section class="content">
  {% if paymentStateResponse is defined and paymentStateResponse is not empty %}
    <ul class="progressbar">
      <li {% if judgedStep >= 1 %}class="active"{% endif %}>{{ "barion.cart"|trans }}</li>
      <li {% if judgedStep >= 2 %}class="active"{% endif %}>{{ "barion.transaction"|trans }}</li>
      <li {% if judgedStep >= 3 %}class="active"{% endif %}>{{ "barion.done"|trans }}</li>
    </ul>
    <h1>{{ paymentStateResponse.POSName }}</h1>
    <h3>{{ "barion.Your.payment.of"|trans }} <strong>{{ paymentStateResponse.total }}&nbsp;{{ paymentStateResponse.currency }}</strong></h3>
    {% if judgedStatus == 1 %}
      <div class="result" style="background-color: {{ waitingRoomPositiveFeedbackColor }}">{{ "barion.transaction.success"|trans }}</div>
    {% elseif judgedStatus == -1 %}
      <div class="result" style="background-color: {{ waitingRoomNegativeFeedbackColor }}">{{ "barion.transaction.failed"|trans }}</div>
    {% else %}
      <div class="result" style="background-color: {{ waitingRoomNeturalFeedbackColor }}">{{ "barion.transaction.netural"|trans }}</div>
    {% endif %}
  {% endif %}
  {% if msg is defined %}
    <p class="msg">{{ msg }}</p>
  {% endif %}
  <a href="{{ paymentStateResponse.paymentRequest.savedRedirectUrl|default(path(webshopDefaultRoute)) }}" class="back">{{ "barion.back.to.the.webshop"|trans }}</a>
  {% if paymentStateResponse is defined and paymentStateResponse is not empty %}
    <img src="{{ asset('/bundles/vaszevbarion/images/barion-card-payment-mark-2017-500px.png') }}" alt="Barion smart gateway" title="Barion smart gateway">
  {% endif %}
</section>
{% include '@VaszevBarion/barion/pixel.html.twig' %}
{% if judgedRefresh is defined and judgedRefresh %}
  <script type="text/javascript">
    setTimeout(function () {
      window.location.replace('{{ path('bairon_waiting_room_check',{'paymentId':paymentStateResponse.paymentId,'tries':tries}) }}');
    }, 5000);
  </script>
{% endif %}
</body>
</html>